### ISSUE TITLE
question about Semantic_Subsequence_Preserving

### ISSUE THREAD

**Issue by VaeReol** [Navidfoumani/EEG2Rep#2]
Hello, I'm a beginner and I really appreciate you sharing your excellent work. I have a few questions I hope you can help me with:

1. In the Semantic_Subsequence_Preserving part of the code, I noticed that you randomly select start_points, which may cause some chunks to overlap. My understanding is that the final output represents the visible_part. For example, if the mask ratio is 50%, would this result in the visible_part in the final output being less than 50%? Is this reasonable?

2. In the code index_chunk = Semantic_Subsequence_Preserving(index, 2, self.mask_ratio), does the '2' refer to the numbers of blocks in Figure 4? Should it be changed to 3 as described in the paper?

Thank you for taking the time to answer my questions.

**Comment by Navidfoumani** [comment]
Thank you so much for your kind words and for diving into our work. I'm happy to help with your questions:
**Number of Chunks in the Code:**
You are correct that the number should be set to 3 to replicate the results described in the paper. While our experiments found that using 3 chunks generally yielded the best results, 1 or 2 chunks could perform better on different EEG datasets. However, for the datasets used in our paper, 3 chunks provided the best overall.
**Overlap in Chunks and Visible Part:**
In the Semantic_Subsequence_Preserving part of the code, as mentioned in Section 2.3 of the paper, we randomly preserve individual time steps until we reach the targeted number of preserved time steps.

Additionally, we included new experimental results in the latest version of the paper on masking ratios. We found that conservative masking (10%) and aggressive masking (90%) lead to learning low-level representations. So, if you try a masking range of 30-70%, you'll generally get good results.
