### ISSUE TITLE
Request for Pretrained Model Checkpoints for EEG2Rep

### ISSUE THREAD

**Issue by slingyu918** [Navidfoumani/EEG2Rep#3]
Dear Authors,
Thank you for sharing your excellent work on EEG2Rep and making the code publicly available. It has been incredibly helpful for my research on physiological signal representation learning.
I was wondering if you could kindly provide the pretrained model checkpoints mentioned in the paper or used during the experiments. Having access to these checkpoints would greatly assist in reproducing your results and further exploring the applications of EEG2Rep in my own research tasks.
If possible, I would greatly appreciate any guidance on how to download or use these checkpoints with the provided codebase.
Thank you in advance for your time and support! Looking forward to your reply.

**Comment by Navidfoumani** [comment]
Hi,

Thanks for your kind words! 
I’ll upload the pre-trained model checkpoints ASAP and update the repo with instructions. 
Let me know if you have any other questions!

Best,
Navid
